language: csharp
mono: none
dist: xenial
dotnet: 2.2
before_install:
 - docker build --tag steinho/nbicreferences -f "Nbic.References/Dockerfile" . 
deploy:
  skip_cleanup: true
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master