language: csharp
mono: none
dist: xenial
dotnet: 3.0.100
install:
 - dotnet restore
script:
 - dotnet build
 - dotnet test Nbic.References.Tests\Nbic.References.Tests.csproj
 - docker build --tag steinhoem/nbicreferences -f "Nbic.References/Dockerfile" . 
deploy:
  skip_cleanup: true
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
