// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nbic.References.EFCore;

namespace Nbic.References.EFCore.Migrations.SqliteMigrations
{
    [DbContext(typeof(SqliteReferencesDbContext))]
    [Migration("20200203141321_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854");

            modelBuilder.Entity("Nbic.References.Public.Models.Reference", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnName("Id")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ApplicationId")
                        .HasColumnName("ApplicationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .HasColumnType("TEXT")
                        .IsUnicode(false);

                    b.Property<string>("Bibliography")
                        .HasColumnType("TEXT")
                        .IsUnicode(false);

                    b.Property<DateTime>("EditDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("date('now')");

                    b.Property<string>("Firstname")
                        .HasColumnType("TEXT")
                        .IsUnicode(false);

                    b.Property<string>("Journal")
                        .HasColumnType("TEXT")
                        .IsUnicode(false);

                    b.Property<string>("Keywords")
                        .HasColumnType("TEXT")
                        .IsUnicode(false);

                    b.Property<string>("Lastname")
                        .HasColumnType("TEXT")
                        .IsUnicode(false);

                    b.Property<string>("Middlename")
                        .HasColumnType("TEXT")
                        .IsUnicode(false);

                    b.Property<string>("Pages")
                        .HasColumnType("TEXT")
                        .IsUnicode(false);

                    b.Property<string>("ReferenceString")
                        .HasColumnName("ReferenceString")
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT")
                        .IsUnicode(false);

                    b.Property<string>("Title")
                        .HasColumnType("TEXT")
                        .IsUnicode(false);

                    b.Property<string>("Url")
                        .HasColumnName("Url")
                        .HasColumnType("TEXT")
                        .IsUnicode(false);

                    b.Property<Guid>("UserId")
                        .HasColumnName("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Volume")
                        .HasColumnType("TEXT")
                        .IsUnicode(false);

                    b.Property<string>("Year")
                        .HasColumnType("TEXT")
                        .IsUnicode(false);

                    b.HasKey("Id")
                        .HasName("PK_Id");

                    b.HasIndex("UserId", "ApplicationId")
                        .HasName("IX_UserId_ApplicationId");

                    b.ToTable("Reference");
                });

            modelBuilder.Entity("Nbic.References.Public.Models.ReferenceUsage", b =>
                {
                    b.Property<Guid>("ReferenceId")
                        .HasColumnName("ReferenceId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ApplicationId")
                        .HasColumnName("ApplicationId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnName("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("ReferenceId", "ApplicationId", "UserId");

                    b.ToTable("ReferenceUsage");
                });

            modelBuilder.Entity("Nbic.References.Public.Models.ReferenceUsage", b =>
                {
                    b.HasOne("Nbic.References.Public.Models.Reference", "Reference")
                        .WithMany("ReferenceUsage")
                        .HasForeignKey("ReferenceId")
                        .HasConstraintName("FK_ReferenceUsage_Reference")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
